# Generated by Django 4.2.1 on 2023-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='field_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='field_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
