# Generated by Django 4.2.1 on 2023-05-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_alter_test_field_file_alter_test_field_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='field_file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='field_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
